spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # System.out.print\uB85C \uCD9C\uB825 (\uC2E4\uBB34 \uC0AC\uC6A9 X)
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger\uB97C \uC774\uC6A9\uD574 \uCD9C\uB825
    org.hibernate.type: trace